// generated by sapper build at 2018-05-04T03:03:00.914Z
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.SAPPER_DEST = require('path').resolve(__dirname, 'build');
process.env.PORT = process.env.PORT || 3000;

console.log('Starting server on port ' + process.env.PORT);
require('./build/server.js');