// This file is generated by Sapper — do not edit it!
import root from '../routes/_layout.html';
import error from '../routes/_error.html';

const d = decodeURIComponent;

const index = {
	js: () => import(/* webpackChunkName: "index" */ '../routes/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const non$45sapper$45redirect$45to = {
	js: () => import(/* webpackChunkName: "non$45sapper$45redirect$45to" */ '../routes/non-sapper-redirect-to.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:non-sapper-redirect-to.html__"
};
const unsafe$45replacement = {
	js: () => import(/* webpackChunkName: "unsafe$45replacement" */ '../routes/unsafe-replacement.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:unsafe-replacement.html__"
};
const preload$45values = {
	js: () => import(/* webpackChunkName: "preload$45values" */ '../routes/preload-values/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:preload-values/index.html__"
};
const preload$45values_custom$45class = {
	js: () => import(/* webpackChunkName: "preload$45values_custom$45class" */ '../routes/preload-values/custom-class.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:preload-values/custom-class.html__"
};
const preload$45values_set = {
	js: () => import(/* webpackChunkName: "preload$45values_set" */ '../routes/preload-values/set.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:preload-values/set.html__"
};
const missing$45index_ok = {
	js: () => import(/* webpackChunkName: "missing$45index_ok" */ '../routes/missing-index/ok.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:missing-index/ok.html__"
};
const redirect$45from = {
	js: () => import(/* webpackChunkName: "redirect$45from" */ '../routes/redirect-from.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:redirect-from.html__"
};
const redirect$45root = {
	js: () => import(/* webpackChunkName: "redirect$45root" */ '../routes/redirect-root.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:redirect-root.html__"
};
const preload$45root = {
	js: () => import(/* webpackChunkName: "preload$45root" */ '../routes/preload-root/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:preload-root/index.html__"
};
const slow$45preload = {
	js: () => import(/* webpackChunkName: "slow$45preload" */ '../routes/slow-preload.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:slow-preload.html__"
};
const credentials = {
	js: () => import(/* webpackChunkName: "credentials" */ '../routes/credentials/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:credentials/index.html__"
};
const delete$45test = {
	js: () => import(/* webpackChunkName: "delete$45test" */ '../routes/delete-test.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:delete-test.html__"
};
const redirect$45to = {
	js: () => import(/* webpackChunkName: "redirect$45to" */ '../routes/redirect-to.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:redirect-to.html__"
};
const about = {
	js: () => import(/* webpackChunkName: "about" */ '../routes/about.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:about.html__"
};
const const_ = {
	js: () => import(/* webpackChunkName: "const_" */ '../routes/const.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:const.html__"
};
const f$252nke = {
	js: () => import(/* webpackChunkName: "f$252nke" */ '../routes/fünke.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:fünke.html__"
};
const store = {
	js: () => import(/* webpackChunkName: "store" */ '../routes/store.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:store.html__"
};
const blog = {
	js: () => import(/* webpackChunkName: "blog" */ '../routes/blog/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/index.html__"
};
const blog_$slug = {
	js: () => import(/* webpackChunkName: "blog_$slug" */ '../routes/blog/[slug].html'),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/[slug].html__"
};
const echo_page_$slug = {
	js: () => import(/* webpackChunkName: "echo_page_$slug" */ '../routes/echo/page/[slug].html'),
	css: "__SAPPER_CSS_PLACEHOLDER:echo/page/[slug].html__"
};
const $x$93_$91y__layout = {
	js: () => import(/* webpackChunkName: "$x$93_$91y__layout" */ '../routes/[x]/[y]/_layout.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:[x]/[y]/_layout.html__"
};
const $x$93_$91y$93_$91z = {
	js: () => import(/* webpackChunkName: "$x$93_$91y$93_$91z" */ '../routes/[x]/[y]/[z].html'),
	css: "__SAPPER_CSS_PLACEHOLDER:[x]/[y]/[z].html__"
};

export const manifest = {
	ignore: [/^\/throw-an-error$/, /^\/credentials\/test.json$/, /^\/f%C3%BCnke.json$/, /^\/blog.json$/, /^\/blog\/([^\/]+?).json$/, /^\/echo\/server-route\/([^\/]+?)$/, /^\/api\/delete\/([^\/]+?)$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// non-sapper-redirect-to.html
			pattern: /^\/non-sapper-redirect-to\/?$/,
			parts: [
				{ component: non$45sapper$45redirect$45to }
			]
		},

		{
			// unsafe-replacement.html
			pattern: /^\/unsafe-replacement\/?$/,
			parts: [
				{ component: unsafe$45replacement }
			]
		},

		{
			// preload-values/index.html
			pattern: /^\/preload-values\/?$/,
			parts: [
				null,
				{ component: preload$45values }
			]
		},

		{
			// preload-values/custom-class.html
			pattern: /^\/preload-values\/custom-class\/?$/,
			parts: [
				null,
				{ component: preload$45values_custom$45class }
			]
		},

		{
			// preload-values/set.html
			pattern: /^\/preload-values\/set\/?$/,
			parts: [
				null,
				{ component: preload$45values_set }
			]
		},

		{
			// missing-index/ok.html
			pattern: /^\/missing-index\/ok\/?$/,
			parts: [
				null,
				{ component: missing$45index_ok }
			]
		},

		{
			// redirect-from.html
			pattern: /^\/redirect-from\/?$/,
			parts: [
				{ component: redirect$45from }
			]
		},

		{
			// redirect-root.html
			pattern: /^\/redirect-root\/?$/,
			parts: [
				{ component: redirect$45root }
			]
		},

		{
			// preload-root/index.html
			pattern: /^\/preload-root\/?$/,
			parts: [
				null,
				{ component: preload$45root }
			]
		},

		{
			// slow-preload.html
			pattern: /^\/slow-preload\/?$/,
			parts: [
				{ component: slow$45preload }
			]
		},

		{
			// credentials/index.html
			pattern: /^\/credentials\/?$/,
			parts: [
				null,
				{ component: credentials }
			]
		},

		{
			// delete-test.html
			pattern: /^\/delete-test\/?$/,
			parts: [
				{ component: delete$45test }
			]
		},

		{
			// redirect-to.html
			pattern: /^\/redirect-to\/?$/,
			parts: [
				{ component: redirect$45to }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ component: about }
			]
		},

		{
			// const.html
			pattern: /^\/const\/?$/,
			parts: [
				{ component: const_ }
			]
		},

		{
			// fünke.html
			pattern: /^\/f%C3%BCnke\/?$/,
			parts: [
				{ component: f$252nke }
			]
		},

		{
			// store.html
			pattern: /^\/store\/?$/,
			parts: [
				{ component: store }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// echo/page/[slug].html
			pattern: /^\/echo\/page\/([^\/]+?)\/?$/,
			parts: [
				null,
				null,
				{ component: echo_page_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// [x]/[y]/[z].html
			pattern: /^\/([^\/]+?)\/([^\/]+?)\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: $x$93_$91y__layout, params: match => ({ x: d(match[1]), y: d(match[2]) }) },
				{ component: $x$93_$91y$93_$91z, params: match => ({ x: d(match[1]), y: d(match[2]), z: d(match[3]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};