// This file is generated by Sapper — do not edit it!
import * as route_throw$45an$45error from '../routes/throw-an-error.js';
import * as route_credentials_test_json from '../routes/credentials/test.json.js';
import * as route_f$252nke_json from '../routes/fünke.json.js';
import * as route_blog_json from '../routes/blog/index.json.js';
import * as route_blog_$slug_json from '../routes/blog/[slug].json.js';
import * as route_echo_server$45route_$slug from '../routes/echo/server-route/[slug].js';
import * as route_api_delete_$id from '../routes/api/delete/[id].js';
import index from '../routes/index.html';
import non$45sapper$45redirect$45to from '../routes/non-sapper-redirect-to.html';
import unsafe$45replacement from '../routes/unsafe-replacement.html';
import preload$45values from '../routes/preload-values/index.html';
import preload$45values_custom$45class from '../routes/preload-values/custom-class.html';
import preload$45values_set from '../routes/preload-values/set.html';
import missing$45index_ok from '../routes/missing-index/ok.html';
import redirect$45from from '../routes/redirect-from.html';
import redirect$45root from '../routes/redirect-root.html';
import preload$45root from '../routes/preload-root/index.html';
import slow$45preload from '../routes/slow-preload.html';
import credentials from '../routes/credentials/index.html';
import delete$45test from '../routes/delete-test.html';
import redirect$45to from '../routes/redirect-to.html';
import about from '../routes/about.html';
import const_ from '../routes/const.html';
import f$252nke from '../routes/fünke.html';
import store from '../routes/store.html';
import blog from '../routes/blog/index.html';
import blog_$slug from '../routes/blog/[slug].html';
import echo_page_$slug from '../routes/echo/page/[slug].html';
import $x$93_$91y__layout from '../routes/[x]/[y]/_layout.html';
import $x$93_$91y$93_$91z from '../routes/[x]/[y]/[z].html';
import root from '../routes/_layout.html';
import error from '../routes/_error.html';

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// throw-an-error.js
			pattern: /^\/throw-an-error$/,
			handlers: route_throw$45an$45error,
			params: () => ({})
		},

		{
			// credentials/test.json.js
			pattern: /^\/credentials\/test.json$/,
			handlers: route_credentials_test_json,
			params: () => ({})
		},

		{
			// fünke.json.js
			pattern: /^\/f%C3%BCnke.json$/,
			handlers: route_f$252nke_json,
			params: () => ({})
		},

		{
			// blog/index.json.js
			pattern: /^\/blog.json$/,
			handlers: route_blog_json,
			params: () => ({})
		},

		{
			// blog/[slug].json.js
			pattern: /^\/blog\/([^\/]+?).json$/,
			handlers: route_blog_$slug_json,
			params: match => ({ slug: d(match[1]) })
		},

		{
			// echo/server-route/[slug].js
			pattern: /^\/echo\/server-route\/([^\/]+?)$/,
			handlers: route_echo_server$45route_$slug,
			params: match => ({ slug: d(match[1]) })
		},

		{
			// api/delete/[id].js
			pattern: /^\/api\/delete\/([^\/]+?)$/,
			handlers: route_api_delete_$id,
			params: match => ({ id: d(match[1]) })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// non-sapper-redirect-to.html
			pattern: /^\/non-sapper-redirect-to\/?$/,
			parts: [
				{ name: "non$45sapper$45redirect$45to", file: "non-sapper-redirect-to.html", component: non$45sapper$45redirect$45to }
			]
		},

		{
			// unsafe-replacement.html
			pattern: /^\/unsafe-replacement\/?$/,
			parts: [
				{ name: "unsafe$45replacement", file: "unsafe-replacement.html", component: unsafe$45replacement }
			]
		},

		{
			// preload-values/index.html
			pattern: /^\/preload-values\/?$/,
			parts: [
				null,
				{ name: "preload$45values", file: "preload-values/index.html", component: preload$45values }
			]
		},

		{
			// preload-values/custom-class.html
			pattern: /^\/preload-values\/custom-class\/?$/,
			parts: [
				null,
				{ name: "preload$45values_custom$45class", file: "preload-values/custom-class.html", component: preload$45values_custom$45class }
			]
		},

		{
			// preload-values/set.html
			pattern: /^\/preload-values\/set\/?$/,
			parts: [
				null,
				{ name: "preload$45values_set", file: "preload-values/set.html", component: preload$45values_set }
			]
		},

		{
			// missing-index/ok.html
			pattern: /^\/missing-index\/ok\/?$/,
			parts: [
				null,
				{ name: "missing$45index_ok", file: "missing-index/ok.html", component: missing$45index_ok }
			]
		},

		{
			// redirect-from.html
			pattern: /^\/redirect-from\/?$/,
			parts: [
				{ name: "redirect$45from", file: "redirect-from.html", component: redirect$45from }
			]
		},

		{
			// redirect-root.html
			pattern: /^\/redirect-root\/?$/,
			parts: [
				{ name: "redirect$45root", file: "redirect-root.html", component: redirect$45root }
			]
		},

		{
			// preload-root/index.html
			pattern: /^\/preload-root\/?$/,
			parts: [
				null,
				{ name: "preload$45root", file: "preload-root/index.html", component: preload$45root }
			]
		},

		{
			// slow-preload.html
			pattern: /^\/slow-preload\/?$/,
			parts: [
				{ name: "slow$45preload", file: "slow-preload.html", component: slow$45preload }
			]
		},

		{
			// credentials/index.html
			pattern: /^\/credentials\/?$/,
			parts: [
				null,
				{ name: "credentials", file: "credentials/index.html", component: credentials }
			]
		},

		{
			// delete-test.html
			pattern: /^\/delete-test\/?$/,
			parts: [
				{ name: "delete$45test", file: "delete-test.html", component: delete$45test }
			]
		},

		{
			// redirect-to.html
			pattern: /^\/redirect-to\/?$/,
			parts: [
				{ name: "redirect$45to", file: "redirect-to.html", component: redirect$45to }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.html", component: about }
			]
		},

		{
			// const.html
			pattern: /^\/const\/?$/,
			parts: [
				{ name: "const_", file: "const.html", component: const_ }
			]
		},

		{
			// fünke.html
			pattern: /^\/f%C3%BCnke\/?$/,
			parts: [
				{ name: "f$252nke", file: "fünke.html", component: f$252nke }
			]
		},

		{
			// store.html
			pattern: /^\/store\/?$/,
			parts: [
				{ name: "store", file: "store.html", component: store }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ name: "blog", file: "blog/index.html", component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "blog_$slug", file: "blog/[slug].html", component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// echo/page/[slug].html
			pattern: /^\/echo\/page\/([^\/]+?)\/?$/,
			parts: [
				null,
				null,
				{ name: "echo_page_$slug", file: "echo/page/[slug].html", component: echo_page_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// [x]/[y]/[z].html
			pattern: /^\/([^\/]+?)\/([^\/]+?)\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "$x$93_$91y__layout", file: "[x]/[y]/_layout.html", component: $x$93_$91y__layout, params: match => ({ x: d(match[1]), y: d(match[2]) }) },
				{ name: "$x$93_$91y$93_$91z", file: "[x]/[y]/[z].html", component: $x$93_$91y$93_$91z, params: match => ({ x: d(match[1]), y: d(match[2]), z: d(match[3]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};