// This file is generated by Sapper — do not edit it!
export const timestamp = 1537372892007;

export const files = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/1b495d0233ee9a023603/credentials.12.js",
	"client/1b495d0233ee9a023603/main.js",
	"client/1b495d0233ee9a023603/non$45sapper$45redirect$45to.2.js",
	"client/1b495d0233ee9a023603/unsafe$45replacement.3.js",
	"client/1b495d0233ee9a023603/preload$45values.4.js",
	"client/1b495d0233ee9a023603/preload$45values_custom$45class.5.js",
	"client/1b495d0233ee9a023603/preload$45values_set.6.js",
	"client/1b495d0233ee9a023603/missing$45index_ok.7.js",
	"client/1b495d0233ee9a023603/redirect$45from.8.js",
	"client/1b495d0233ee9a023603/redirect$45root.9.js",
	"client/1b495d0233ee9a023603/preload$45root.10.js",
	"client/1b495d0233ee9a023603/slow$45preload.11.js",
	"client/1b495d0233ee9a023603/index.1.js",
	"client/1b495d0233ee9a023603/delete$45test.13.js",
	"client/1b495d0233ee9a023603/redirect$45to.14.js",
	"client/1b495d0233ee9a023603/about.15.js",
	"client/1b495d0233ee9a023603/const_.16.js",
	"client/1b495d0233ee9a023603/f$252nke.17.js",
	"client/1b495d0233ee9a023603/store.18.js",
	"client/1b495d0233ee9a023603/blog.19.js",
	"client/1b495d0233ee9a023603/blog_$slug.20.js",
	"client/1b495d0233ee9a023603/echo_page_$slug.21.js",
	"client/1b495d0233ee9a023603/$x$93_$91y__layout.22.js",
	"client/1b495d0233ee9a023603/$x$93_$91y$93_$91z.23.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/non-sapper-redirect-to\/?$/ },
	{ pattern: /^\/unsafe-replacement\/?$/ },
	{ pattern: /^\/preload-values\/?$/ },
	{ pattern: /^\/preload-values\/custom-class\/?$/ },
	{ pattern: /^\/preload-values\/set\/?$/ },
	{ pattern: /^\/missing-index\/ok\/?$/ },
	{ pattern: /^\/redirect-from\/?$/ },
	{ pattern: /^\/redirect-root\/?$/ },
	{ pattern: /^\/preload-root\/?$/ },
	{ pattern: /^\/slow-preload\/?$/ },
	{ pattern: /^\/credentials\/?$/ },
	{ pattern: /^\/delete-test\/?$/ },
	{ pattern: /^\/redirect-to\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/const\/?$/ },
	{ pattern: /^\/f%C3%BCnke\/?$/ },
	{ pattern: /^\/store\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ },
	{ pattern: /^\/echo\/page\/([^\/]+?)\/?$/ },
	{ pattern: /^\/([^\/]+?)\/([^\/]+?)\/([^\/]+?)\/?$/ }
];